"""Runtime-wide constants for NUTANAA Studio OS."""

# Agent statuses
AGENT_STATUS_IDLE = "idle"
AGENT_STATUS_RUNNING = "running"
AGENT_STATUS_PAUSED = "paused"
AGENT_STATUS_CANCELLED = "cancelled"
AGENT_STATUS_COMPLETED = "completed"
AGENT_STATUS_ERROR = "error"

# Workflow statuses
WORKFLOW_STATUS_PENDING = "pending"
WORKFLOW_STATUS_RUNNING = "running"
WORKFLOW_STATUS_PAUSED = "paused"
WORKFLOW_STATUS_CANCELLED = "cancelled"
WORKFLOW_STATUS_COMPLETED = "completed"
WORKFLOW_STATUS_FAILED = "failed"
WORKFLOW_STATUS_ROLLED_BACK = "rolled_back"

# Plugin statuses
PLUGIN_STATUS_INSTALLED = "installed"
PLUGIN_STATUS_UNINSTALLED = "uninstalled"
PLUGIN_STATUS_ENABLED = "enabled"
PLUGIN_STATUS_DISABLED = "disabled"

# Default values
DEFAULT_PROVIDER_TIMEOUT = 30
DEFAULT_AGENT_TIMEOUT = 30
DEFAULT_WORKFLOW_TIMEOUT = 60
DEFAULT_MAX_ITERATIONS = 5

# Environment variable names
ENV_LOG_LEVEL = "NUTANAA_LOG_LEVEL"
ENV_PROVIDER_DEFAULT = "NUTANAA_DEFAULT_PROVIDER"
ENV_CONFIG_PATH = "NUTANAA_CONFIG_PATH"
